### ISSUE TITLE
Backend Disconnection on a bit of heavy operations

### ISSUE THREAD

**Issue by friedrice123** [Cs-253-Team-4/Cs-253-Team-4-Evensplit#11]
On working a bit on the group feature, we found out that the website gets corrupted easily and frequently. For ex we made a group with 7 people and when we entered an amount and tried to split it among all 7 members, it resulted in the backend getting disconnected and showing runtime errors and most parts of the website become unresponsive. To resolve this one has to again connect backend from terminal, sign out and again login. 

This is a huge bug in the website and should be removed with almost priority
![image](https://user-images.githubusercontent.com/103812705/230790216-27c45a55-caa1-4be2-9aca-26212764715a.png)

**Comment by TheMihirD** [comment]
Resolved.
