### ISSUE TITLE
Events already showing on Website 

### ISSUE THREAD

**Issue by friedrice123** [Cs-253-Team-4/Cs-253-Team-4-Evensplit#5]
There are already some events present on every user's Calendar page, which are not needed like "CS253 Deadline" which is not a deadline every user should see.
![image](https://user-images.githubusercontent.com/103812705/230787845-af31ba0b-0c9e-4708-ba20-9636d1d4e515.png)

**Comment by Mohak-Singh-Rana** [comment]
The events which are already shown on the page are added by the admin. Events added by the admin will be shown on every user's page (These are global events for the whole community).
