### ISSUE TITLE
Showing all users in friends page

### ISSUE THREAD

**Issue by sarthakk21** [Cs-253-Team-4/Cs-253-Team-4-Evensplit#7]
In the friends page, beneath the search option, all user's info is shown there, which I feel is unnecessary. It should just have a search option and if the name/email is correct then the member should be shown.

**Comment by TheMihirD** [comment]
We added it only for the convenience of the user. Using the search bar, he is able to view everybody using the website - whether or not he knows them. If we were to remove this, his activity would be restricted only to his friends and users whose names / emails he happens to guess correctly. We would prefer this component the way it is currently. The working is perfect and there are no logistical drawbacks, hence we wouldn't classify this as a bug. Thank you!
